name: Build
on: [push, pull_request]
jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.9, 3]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install imagemagick
        run: |
          sudo apt-get install -y imagemagick
      # conda does not support environment markers
      - name: Install testing dependencies (Python 3.6+)
        if: ${{ matrix.python-version >= 3.6 }}
        run: |
          conda install -c anaconda -c conda-forge --file requirements-linting-old.txt
      - name: Install mamba for faster py2 resolution
        run: |
          conda install -c anaconda -c conda-forge mamba
      - name: Install testing dependencies
        run: |
          mamba install -c anaconda -c conda-forge --file requirements-conda.txt --file requirements-linting-old.txt six packaging pytest coveralls coverage
      - name: Conda info
        run: |
          conda info
          conda list
      - name: Lint with flake8
        # stop the build if there are Python syntax errors or undefined names
        run: flake8 . --show-source
      - name: Test install from setup.py
        run: pip install .
      - run: coverage run -m pytest .
      - run: COVERALLS_REPO_TOKEN=mEQ4sldJtlrG3RzjGVD32EYrjUIj4YCV3 coveralls
